import { keys } from '.';

/**
 * This is the list of most common commands from the Android TV Remote integration page.
 * Not all are ensured to work, and if they do not it is likely an issue with the underlying package used by the Android TV Remote integration or the Android TV Remote Protocol V2 itself.
 * https://www.home-assistant.io/integrations/androidtv_remote/#remote
 */
export const defaultKeys: keys = {
	power: { key: 'POWER', icon: 'mdi:power' },
	volume_up: { key: 'VOLUME_UP', icon: 'mdi:volume-plus' },
	volume_down: { key: 'VOLUME_DOWN', icon: 'mdi:volume-minus' },
	volume_mute: { key: 'MUTE', icon: 'mdi:volume-mute' },
	back: { key: 'BACK', icon: 'mdi:keyboard-backspace' },
	home: { key: 'HOME', icon: 'mdi:home' },
	up: { key: 'DPAD_UP', icon: 'mdi:chevron-up' },
	left: { key: 'DPAD_LEFT', icon: 'mdi:chevron-left' },
	center: { key: 'DPAD_CENTER', icon: 'mdi:checkbox-blank-circle' },
	right: { key: 'DPAD_RIGHT', icon: 'mdi:chevron-right' },
	down: { key: 'DPAD_DOWN', icon: 'mdi:chevron-down' },
	play: { key: 'MEDIA_PLAY', icon: 'mdi:play' },
	pause: { key: 'MEDIA_PAUSE', icon: 'mdi:pause' },
	play_pause: { key: 'MEDIA_PLAY_PAUSE', icon: 'mdi:play-pause' },
	stop: { key: 'MEDIA_STOP', icon: 'mdi:stop' },
	rewind: { key: 'MEDIA_REWIND', icon: 'mdi:rewind' },
	fast_forward: { key: 'MEDIA_FAST_FORWARD', icon: 'mdi:fast-forward' },
	previous: { key: 'MEDIA_PREVIOUS', icon: 'mdi:skip-previous' },
	record: { key: 'MEDIA_RECORD', icon: 'mdi:record' },
	next: { key: 'MEDIA_NEXT', icon: 'mdi:skip-next' },
	menu: { key: 'MENU', icon: 'mdi:menu' },
	a: { key: 'BUTTON_A', icon: 'mdi:alpha-a-circle' },
	b: { key: 'BUTTON_B', icon: 'mdi:alpha-B-circle' },
	x: { key: 'BUTTON_X', icon: 'mdi:alpha-x-circle' },
	y: { key: 'BUTTON_Y', icon: 'mdi:alpha-y-circle' },
	n0: { key: '0', icon: 'mdi:numeric-0' },
	n1: { key: '1', icon: 'mdi:numeric-1' },
	n2: { key: '2', icon: 'mdi:numeric-2' },
	n3: { key: '3', icon: 'mdi:numeric-3' },
	n4: { key: '4', icon: 'mdi:numeric-4' },
	n5: { key: '5', icon: 'mdi:numeric-5' },
	n6: { key: '6', icon: 'mdi:numeric-6' },
	n7: { key: '7', icon: 'mdi:numeric-7' },
	n8: { key: '8', icon: 'mdi:numeric-8' },
	n9: { key: '9', icon: 'mdi:numeric-9' },
	channel_up: { key: 'CHANNEL_UP', icon: 'mdi:arrow-up-circle' },
	channel_down: { key: 'CHANNEL_DOWN', icon: 'mdi:arrow-down-circle' },
	f1: { key: 'F1', icon: 'mdi:keyboard-f1' },
	f2: { key: 'F2', icon: 'mdi:keyboard-f2' },
	f3: { key: 'F3', icon: 'mdi:keyboard-f3' },
	f4: { key: 'F4', icon: 'mdi:keyboard-f4' },
	f5: { key: 'F5', icon: 'mdi:keyboard-f5' },
	f6: { key: 'F6', icon: 'mdi:keyboard-f6' },
	f7: { key: 'F7', icon: 'mdi:keyboard-f7' },
	f8: { key: 'F8', icon: 'mdi:keyboard-f8' },
	f9: { key: 'F9', icon: 'mdi:keyboard-f9' },
	f10: { key: 'F10', icon: 'mdi:keyboard-f10' },
	f11: { key: 'F11', icon: 'mdi:keyboard-f11' },
	f12: { key: 'F12', icon: 'mdi:keyboard-f12' },
	tv: { key: 'TV', icon: 'mdi:television-box' },
	red: { key: 'PROG_RED', icon: 'mdi:alpha-r-box' },
	green: { key: 'PROG_GREEN', icon: 'mdi:alpha-g-box' },
	yellow: { key: 'PROG_YELLOW', icon: 'mdi:alpha-y-box' },
	blue: { key: 'PROG_BLUE', icon: 'mdi:alpha-b-box' },
	button_mode: { key: 'BUTTON_MODE', icon: 'mdi:gesture-tap-buton' },
	explorer: { key: 'EXPLORER', icon: 'mdi:folder-multiple' },
	info: { key: 'INFO', icon: 'mdi:information' },
	guide: { key: 'GUIDE', icon: 'mdi:television-guide' },
	teletext: { key: 'TV_TELETEXT', icon: 'mdi:card-text' },
	captions: { key: 'CAPTIONS', icon: 'mdi:closed-caption' },
	dvr: { key: 'DVR', icon: 'mdi:audio-video' },
	audio_track: { key: 'MEDIA_AUDIO_TRACK', icon: 'mdi:waveform' },
	settings: { key: 'SETTINGS', icon: 'mdi:cog' },
	delete: { key: 'DEL', icon: 'mdi:backspace' },
	forward_delete: { key: 'FOWARD_DEL', icon: 'mdi:backspace-reverse' },
	enter: { key: 'ENTER', icon: 'mdi:magnify' },
	keyboard: { key: 'KEYBOARD', icon: 'mdi:keyboard' },
	search: { key: 'SEARCH', icon: 'mdi:google-assistant' },
	textbox: { key: 'TEXTBOX', icon: 'mdi:text-box' },
};
